### ISSUE TITLE
[SUGESTÃO] Adicionar convenção de commits 

### ISSUE THREAD

**Issue by mauromortoni** [digitalinnovationone/dio-lab-open-source#43796]
## Solução

Configurar um modelo de mensagem de commit personalizado no Git:

1. **Crie o arquivo de modelo:**
	Crie um arquivo de texto que servirá como modelo. Você pode incluir espaços reservados para várias informações que deseja capturar. Por exemplo:

	```text
	# Commit Message Template
	# Prefixos: docs:,feat:,fix:,refactor:,style:,test: (50 caracteres ou menos)
	<prefixo>: <descricao>

	# Tarefa: 
	# Issue-<numero da Issue>
	Tarefa:
	Issue-

	# Solucao: 
	# * <descricao> (72 caracteres ou menos por linha)
	Solucao:
	*
	```

2. **Salve o arquivo de modelo:**
	Salve este arquivo (**templatefile.txt**) em um local seguro onde ele não será excluído ou movido acidentalmente.

3. **Configure o Git para usar o modelo:**
	Configure o Git para usar seu arquivo de modelo, executando o seguinte comando em seu terminal:

	 ```sh
	 git config --global commit.template /path/para/seu/templatefile.txt
	 ```

4. **Crie um commit usando o modelo:**
	Ao criar um commit, o Git abrirá seu editor de texto padrão com o modelo carregado. Você pode então preencher os detalhes conforme especificado em seu modelo. Por exemplo:

	 ```sh
	 git commit
	 ```

	 Este comando abrirá o modelo em seu editor. Veja o modelo em "**1.**".

Criar script shell para impor as regras de mensagens de commit:

O gancho "**commit-msg**" tem como objetivo ajudar os desenvolvedores a formalizar mensagens de commit. Ele verifica a mensagem de commit digitada quanto à presença do modelo especificado e recusa o commit se a mensagem não corresponder ao modelo.

1. **Crie o gancho "commit-msg":**
* na pasta "**seu projeto/.git/hooks/**";
* executar: cp commit-msg.sample commit-msg;
* abrir "**commit-msg**" no editor de texto;
* apagar o conteúdo original e inserir o conteúdo de "**Bash Script: .git\hooks\commit-msg**", abaixo;
* Salvar o arquivo.

Seguindo essas etapas, você pode garantir que suas mensagens de commit sejam informativas, consistentes e úteis para qualquer pessoa que esteja revisando o histórico do seu projeto.

Ao executar o comando "**git commit**" na pasta raiz do seu projeto:
+ será aberto o editor de texto com o modelo mais pendências do commit, configurado como padrão;
+ preencha suas mensagens como descrito em "**modelo**", acima; e
+ salvar a sua edição e fechar o editor.

O gancho do Git fará seu trabalho nesta tarefa - notificará sobre o primeiro erro encontrado se o modelo não foi seguido ou a mensagem "**Commit conforme a convenção, parabéns!**"

Bash Script: .git\hooks\commit-msg
```bash
#!/usr/bin/env bash

# regex para validar a mensagem do commit
# chamado quando o usuario executa o comando git commit -m
# Garantindo que a convenção seja seguida nas mensagens

# cores
RED='\033[0;31m'
NC='\033[0m' # No Color
YELLOW='\033[1;33m'
GREEN='\033[0;32m'

message=$(grep -v '#' $1)

# Especifique o tipo de commit
error_msg="❌${RED}Commit abortado.${NC} Você deve adicionar um ${YELLOW}prefixo${NC} para o titulo do commit exemplo: \n"\
"\t${YELLOW}docs:${NC} Altera a documentação do projeto. ${GREEN}(Exemplo: docs: update README.md)\n"\
"\t${YELLOW}feat:${NC} Adiciona uma nova funcionalidade ao projeto. ${GREEN}(Exemplo: feat: add USENAME.md profile)\n"\
"\t${YELLOW}fix:${NC} Corrige um bug ou problema no projeto. (${GREEN}Exemplo: fix: fixed issue fix#IssueNumber)\n"\
"\t${YELLOW}refactor:${NC} Realiza mudanças no código que não alteram a funcionalidade. ${GREEN}(Exemplo: refactor: refactor at CLASSNAME)\n"\
"\t${YELLOW}style:${NC} Realiza mudanças na aparência, sem alterar a funcionalidade. (${GREEN}Exemplo: style: add EFFECTNAME to COMPONENT)\n"\
"\t${YELLOW}test:${NC} Adiciona ou modifica testes no projeto. ${GREEN}(Exemplo: test: add unit test for UserService)\n"\
"\n"\
"${YELLOW}<prefixo>: Adicionar convenção de commits no Guia de Contribuição\n"\
"\n"\
"Tarefa:\n"\
"Issue-43225\n"\
"\n"\
"Solucao:\n"\
"* Script shell para impor suas regras de mensagens de commit: ~\.git\hooks\commit-msg\n"\
"* Seven-rules\n"\
"* 1. Separate subject from body with a blank line\n"\
"* 2. Limit the subject line to 50 characters\n"\
"* 3. Capitalize the subject line\n"\
"* 4. Do not end the subject line with a period\n"\
"* 5. Use the imperative mood in the subject line\n"\
"* 6. Wrap the body at 72 characters\n"\
"* 7. Use the body to explain what and why vs. how\n"\

commit_types
commit_regex='(^docs:|^feat:|^fix:|^refactor:|^style:|^test:)'

# Without the type of commit
if [[ "$message" =~ ${commit_regex} ]]; then
    echo 
else
	printf "$error_msg"
    exit 1
fi

# Constant
max_size=50
start_word="Tarefa:"
end_word="Solucao:"
word_after_blank_line=(Tarefa: Solucao:)

# 1. Separate subject from body with a blank line
# Check for a blank line before the word 'target_word'
element_count=${#word_after_blank_line[*]}
index=0

while [ "$index" -lt "$element_count" ]
do    # List all the elements in the array.
  echo "$message" | grep -B1 ${word_after_blank_line[$index]} | grep -q '^$'
  
  if [ $? != 0 ]; then
	echo -e "${RED}Commit abortado.${NC} Não há linha em branco antes da palavra '${word_after_blank_line[$index]}'. \n" >&2
	exit 1	
  fi  
  
  ((index++))
done

# 2. Limit the subject line to 50 characters
error_msg="${RED}Commit abortado.${NC} O título do commit  deve ter no máximo ${max_size} caracteres: \n"

extracted_string=$(echo "$message" | tr '\n' ' ' | sed -n "s/.*$start_word \(.*\) $end_word.*/\1/p" | awk '{$1=$1;print}')

if ((${#extracted_string}>${max_size})); then
    echo -e "$error_msg" >&2
    exit 1
fi

error_msg="${RED}Commit abortado.${NC} O commit deve conter a palavra 'Tarefa:' antes do número da Issue.\n"\
"${YELLOW}Exemplo:${NC}\n"\
"${GREEN}Tarefa:${NC}\n"\
"TG-01"

# Count lines containing the word 'Tarefa:' at the beginning of the line
count=$(echo "$message" | grep -c "^Tarefa:")

if (( $count == 0 )); then	
    echo -e "$error_msg" >&2
    exit 1
fi

error_msg="${RED}Commit abortado.${NC} Você deve adicionar o número da sua tarefa na Issue.\n"\
"${YELLOW}Exemplo:${NC}\n"\
"${GREEN}Issue-01${NC}"

search_word="^Issue-"

# Count occurrences of 'search_word' followed by numbers
count=$(echo "$message" | grep -o "${search_word}[0-9]\+" | wc -l)
          
if (( $count == 0 )); then
    echo -e "$error_msg" >&2
    exit 1
fi

error_msg="${RED}Commit abortado.${NC} O commit deve conter a palavra 'Solucao:' antes da lista de o que foi feito.\n"\
"${YELLOW}Solucao:${NC}\n"

# Count lines containing the word 'Solucao:' at the beginning of the line
count=$(echo "$message" | grep -c "^Solucao:")

if (( $count == 0 )); then	
    echo -e "$error_msg" >&2
    exit 1
fi

commit_regex='(\* [a-z0-9]+)'
error_msg="${RED}Commit abortado.${NC} O commit deve conter uma lista de o que foi feito.\n"\
"${YELLOW}* Adicionado o CSS para a pagina de login${NC}\n"\
"${YELLOW}* Criado a validacao do campo de email${NC}\n"

# Count occurrences of 'search_word' followed by numbers
count=$(echo "$message" | grep -o "^*" | wc -l)
          
if (( $count == 0 )); then
    echo -e "$error_msg" >&2
    exit 1
fi

echo -e "${GREEN}Commit conforme a convenção, parabéns!${NC}\n"
``` 
### Todo

- [ ] melhorar o código e regex (Mauro Mortoni, 07/08/2024) 
- [ ] Criar script para instalação da solução (Mauro Mortoni, 07/08/2024) 
  - [ ] Sub-task or description  

### In Progress

- [ ] Work on Github Repo [JIRA-345]  

### Done ✓

- [x] Create my first TODO.md  

## Referências
[<img align="left" height="34px" width="94px" alt="Git" src="https://git-scm.com/images/logo@2x.png">](https://git-scm.com/docs/githooks)
<br/>
<br/>
[<img align="left" height="34px" width="94px" alt="Atlassian" src="https://wac-cdn.atlassian.com/misc-assets/adg4-nav/AtlassianHeaderLogo.svg">](https://www.atlassian.com/git/tutorials/git-hooks)
<br/>
<br/>
[Advanced Bash-Scripting Guide](https://tldp.org/LDP/abs/html/)
<br/>
<br/>
[<img align="left" height="34px" width="94px" alt="Linux Bash Shell Scripting Tutorial" src="https://www.cyberciti.biz/media/new/cms/2017/06/new-nixcraft-logo-cyberciti.biz_.png">](https://bash.cyberciti.biz/guide/Main_Page)
